version: "3"
services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    volumes:
      - ./client/src:/client/src
    container_name: client-dev
    depends_on:
      - server

  server:
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server-dev
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
      - ./server/src:/server/src
    command: npm run dev
